./" http://www.linuxfocus.org/English/November2003/article309.shtml"
.TH convdict12 1 "August 12, 2009" "version 0.1" "USER COMMANDS"
.SH NAME
convdict12 \- converts Wikt dictionary format1 file to format2 file
.SH SYNOPSIS
.B convdict12
[SOURCE] [ERRATADIR] [DESTINATION]
.SH DESCRIPTION
.SH SEE ALSO
convdict23(1)
convdict34(1)
wikt(1)
