./" http://www.linuxfocus.org/English/November2003/article309.shtml"
.TH convdict34 1 "August 12, 2009" "version 0.2" "USER COMMANDS"
.SH NAME
convdict34 \- converts Wikt dictionary format3 file to format4 file
.SH SYNOPSIS
.B convdict34
[option]... [SOURCE] [DESTINATION]
.SH DESCRIPTION
convdict34 converts format3 file to format4.
.SH OPTIONS
.TP
\-f, \-\-from=NUMBER
sets the starting offset
.TP
\-t, \-\-to=NUMBER
sets the ending offset
.TP
\-\-names
displays names of entries
.TP
SOURCE
Format3 input file.
.TP
DESTINATION
Output file. Existing file will be overwritten.
.SH SEE ALSO
convdict12(1)
convdict23(1)
wikt(1)
